# Generated by Django 3.2.5 on 2021-09-20 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210909_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumuser',
            name='numero_tarjeta',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='CarteraInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(max_length=6)),
                ('descripcion', models.CharField(max_length=150)),
                ('precio_compra', models.FloatField()),
                ('cantidad_compra', models.IntegerField()),
                ('fecha_compra', models.DateField()),
                ('cantidad_posesion', models.IntegerField()),
                ('precio_ult_venta', models.FloatField()),
                ('ganancias_perdidas', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
