# Generated by Django 3.2.5 on 2021-09-20 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210919_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carterainversion',
            old_name='cantidad_posesion',
            new_name='cantidad_venta',
        ),
    ]
