# Generated by Django 3.2.5 on 2021-09-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_cantidad_posesion_carterainversion_cantidad_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carterainversion',
            name='cantidad_venta',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='carterainversion',
            name='ganancias_perdidas',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='carterainversion',
            name='precio_ult_venta',
            field=models.FloatField(blank=True),
        ),
    ]
