# Generated by Django 3.2.5 on 2021-09-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210920_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carterainversion',
            name='cantidad_venta',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='carterainversion',
            name='ganancias_perdidas',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='carterainversion',
            name='precio_ult_venta',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
