# Generated by Django 3.2.5 on 2021-10-04 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211003_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumuser',
            name='asesor',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.asesor'),
        ),
    ]
