# Generated by Django 3.2.5 on 2021-10-04 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_premiumuser_asesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumuser',
            name='asesor',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.asesor'),
        ),
    ]
