# Generated by Django 3.2.5 on 2021-10-04 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_premiumuser_asesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumuser',
            name='asesor',
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='asesor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.asesor'),
        ),
    ]
