# Generated by Django 3.2.5 on 2021-10-04 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211003_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiumuser',
            old_name='asesor_id',
            new_name='asesor',
        ),
    ]
