# Generated by Django 3.2.5 on 2021-10-04 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_asesor_id_premiumuser_asesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiumuser',
            old_name='asesor',
            new_name='asesor_id',
        ),
    ]
